import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_components/footer";
import { AuthProvider } from "@/app/_lib/AuthContext";
import Navbar from "./_components/navbar";
import { redirect } from "next/navigation";
import Menu from "./_components/menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="drawer lg:drawer-open">
            <input id="my-drawer-4" type="checkbox" className="drawer-toggle" />
            <div className="drawer-content flex flex-col min-h-screen">
              <Navbar />
              <main className="flex justify-center flex-1 bg-base-200">
                {children}
              </main>
              <Footer />
            </div>
            <div className="drawer-side is-drawer-close:overflow-visible border-r-2 border-r-base-200">
              <label
                htmlFor="my-drawer-4"
                aria-label="close sidebar"
                className="drawer-overlay"
              ></label>
              <Menu />
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
